"""Constants for Gobbler MCP server.

Centralizes magic numbers and configuration limits used throughout the codebase.
"""

# Crawling limits
MAX_CRAWL_DEPTH = 5
MAX_PAGES_PER_CRAWL = 500
MAX_VIDEOS_PER_PLAYLIST = 500
MAX_CONCURRENCY_CRAWL = 10

# Timeout limits (seconds)
MIN_TIMEOUT = 5
MAX_TIMEOUT = 120
DEFAULT_TIMEOUT = 30

# Script execution timeouts (seconds)
MIN_SCRIPT_TIMEOUT = 1
MAX_SCRIPT_TIMEOUT = 150
DEFAULT_SCRIPT_TIMEOUT = 30

# Queue thresholds
AUTO_QUEUE_VIDEO_THRESHOLD = 10
AUTO_QUEUE_URL_THRESHOLD = 10
AUTO_QUEUE_FILE_THRESHOLD = 10
AUTO_QUEUE_SIZE_THRESHOLD_MB = 500

# Batch processing limits
MAX_BATCH_URLS = 100
MAX_BATCH_CONCURRENCY_WEBPAGE = 10
DEFAULT_BATCH_CONCURRENCY_WEBPAGE = 5
MAX_BATCH_CONCURRENCY_AUDIO = 4
DEFAULT_BATCH_CONCURRENCY_AUDIO = 2
MAX_BATCH_CONCURRENCY_DOCUMENT = 5
DEFAULT_BATCH_CONCURRENCY_DOCUMENT = 3
MAX_BATCH_CONCURRENCY_YOUTUBE = 10
DEFAULT_BATCH_CONCURRENCY_YOUTUBE = 2

# Crawl delays and jitter
DEFAULT_CRAWL_DELAY = 1.0
DEFAULT_JITTER_RANGE = 1.0
DEFAULT_YOUTUBE_DELAY = 1.5

# Retry configuration
MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0

# Job queue limits
MAX_JOBS_LIST = 100
DEFAULT_JOBS_LIST = 20
